//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shelly_UI.Assets {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_pt_PT {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_pt_PT() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Shelly_UI.Assets.Resources_pt_PT", typeof(Resources_pt_PT).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ActionReinstalling {
            get {
                return ResourceManager.GetString("ActionReinstalling", resourceCulture);
            }
        }
        
        internal static string ActionInstalling {
            get {
                return ResourceManager.GetString("ActionInstalling", resourceCulture);
            }
        }
        
        internal static string ActionDownloading {
            get {
                return ResourceManager.GetString("ActionDownloading", resourceCulture);
            }
        }
        
        internal static string ActionCheckingConflicts {
            get {
                return ResourceManager.GetString("ActionCheckingConflicts", resourceCulture);
            }
        }
        
        internal static string AccentHexColor {
            get {
                return ResourceManager.GetString("AccentHexColor", resourceCulture);
            }
        }
        
        internal static string ActionRemoving {
            get {
                return ResourceManager.GetString("ActionRemoving", resourceCulture);
            }
        }
        
        internal static string ActionRunningHooks {
            get {
                return ResourceManager.GetString("ActionRunningHooks", resourceCulture);
            }
        }
        
        internal static string ActionUpdating {
            get {
                return ResourceManager.GetString("ActionUpdating", resourceCulture);
            }
        }
        
        internal static string AlpmUpdatePromptDialog {
            get {
                return ResourceManager.GetString("AlpmUpdatePromptDialog", resourceCulture);
            }
        }
        
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        internal static string ApplyAccent {
            get {
                return ResourceManager.GetString("ApplyAccent", resourceCulture);
            }
        }
        
        internal static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        internal static string ArchNews {
            get {
                return ResourceManager.GetString("ArchNews", resourceCulture);
            }
        }
    }
}
